### PR TITLE
MacOs fix for ANSI Keyboards

### PR DESCRIPTION
**Pull request by elordeiro**
This fixes the issue where ANSI keyboards don't output anything when the Tilde key is pressed. 

To fix the issue, run the macos_fix.py script. This will rename the custom layout under us/keylayouts to custom_iso and they it will make a copy of this file, make the necessary modifications and save the new changes under custom_ansi. 

This also fixes an issue where when typing passwords in the terminal or login and typing in spotlight, macos would always revert back to the default layout. A unique keyboard ID is required. 

Let me know if you have any preferences on how the code should be structured. I initially had it all inside of generate.py but then i realized that it was this simple fix was longer than the whole generate.py file so I split it into its own file.

### CODE REVIEW

**Comment by nick-gravgaard** [comment]
Thanks for that. It's a lot of code for something I'd hoped would be taken care of by klfc. I've just committed a change which uses simple search and replace, rather than parsing the XML. Can you try out the Mac OS files and tell me if they work?

It sounds like Mac OS has a bug regarding typing passwords in the terminal, logging in, and typing in spotlight. What's the problem with the id (`-1337`) that klfc uses in the file? So far we've only been thinking about the US files, but presumably this issue affects the GB files too. Is that right?

**Comment by elordeiro** [comment]
It doesn't seem to work for me. I believe what's keymaps 0 and 1 need to have both code 10 and 50. Keymap 0 maps both of them to '`' and keymap 1 maps them to '~'. Like this:

Screenshot 2024-06-05 at 7 26 08 PM

But even with both codes in the keymaps there are still issues with typing in the terminal, spotlight and shortcuts that use that key. I suspect there is another built in keyboard layout (Unicode Hex Input) that has that specific ID. When activate that layout I get the bahaviour of the '~' not working but the keys are in their original places. Changing the keyboard ID is what fixes that issue. I got the range for the random number from the Ukelele repo:

https://github.com/sillsdev/Ukelele/blob/bf60297399b33ce6be0bcb3a8eb656ffcc2a0e0c/Ukelele%20Cocoa/ScriptRanges.h#L14

**Comment by elordeiro** [comment]
As far as the global versions go, they just need a new keyboard ID and they work fine.

**Comment by elordeiro** [comment]
Okay, it turns out that keyboard id being unique was a bigger part of the problem than I initially thought. The changes I pushed essentially creates a unique ID for every .keylayout file (both us and gb) and then goes into the change you made of changing code 10 to 50 for us versions only. This seems to have fixed the issue for me for both versions. Keeping in mind that my keyboard is an ANSI one, therefore I don't have an Alt-Gr key to test out the other keys. 

One small note that may be relevant, the key we've been working on produces the chars "\",  "|" in the iso version. When I looked at pictures of an iso keyboard online I saw the chars "`", "¬", "¦" . I don't know if this is the intended behaviour or just a consequence of my keyboard not being a proper ISO Keyboard.

**Comment by nick-gravgaard** [comment]
Good stuff, thanks for your help with this

**Comment by nick-gravgaard** [comment]
@elordeiro FYI, I've just pushed a commit which makes ID generation consistent between runs

**Comment by elordeiro** [comment]
That's even better. I have much to learn. Thank you for letting me contribute.

**Comment by nick-gravgaard** [comment]
No worries - it was a great joint effort :)

**Pull request merged**
